# Enhanced Streamlit App code with error handling
streamlit_code = """
{
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "streamlit_code = '''\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "\n",
    "st.title(\"Titanic Survival Prediction\")\n",
    "\n",
    "try:\n",
    "    model = joblib.load(\"titanic_logistic_model.pkl\")\n",
    "except Exception as e:\n",
    "    st.error(f\"Error loading model: {e}\")\n",
    "    st.stop()\n",
    "\n",
    "Pclass = st.selectbox(\"Passenger Class\", [1,2,3])\n",
    "Sex = st.selectbox(\"Sex\", [\"male\",\"female\"])\n",
    "Age = st.slider(\"Age\", 0, 80, 25)\n",
    "SibSp = st.number_input(\"Siblings/Spouses\", 0, 10, 0)\n",
    "Parch = st.number_input(\"Parents/Children\", 0, 10, 0)\n",
    "Fare = st.slider(\"Fare\", 0, 500, 50)\n",
    "Embarked = st.selectbox(\"Port of Embarkation\", [\"C\",\"Q\",\"S\"])\n",
    "\n",
    "input_df = pd.DataFrame([{\n",
    "    \"Pclass\": Pclass,\n",
    "    \"Sex_male\": 1 if Sex==\"male\" else 0,\n",
    "    \"Age\": Age,\n",
    "    \"SibSp\": SibSp,\n",
    "    \"Parch\": Parch,\n",
    "    \"Fare\": Fare,\n",
    "    \"Embarked_Q\": 1 if Embarked==\"Q\" else 0,\n",
    "    \"Embarked_S\": 1 if Embarked==\"S\" else 0\n",
    "}])\n",
    "\n",
    "if st.button('Predict'):\n",
    "    try:\n",
    "        prediction = model.predict(input_df)[0]\n",
    "        st.success(\"Prediction: \" + (\"Survived\" if prediction==1 else \"Did not survive\"))\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error making prediction: {e}\")\n",
    "'''\n",
    "\n",
    "# Display code for copying\n",
    "print(streamlit_code)"
   ]
  },